
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build the Docker image
      run: docker pull ttl.sh/notify-completion:1h
      
    - name: Tag changed
      run: docker tag ttl.sh/notify-completion:1h akash7778/notify-completion:1h
      
    - name: Sign and push docker image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "akash7778/notify-completion:1h"
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
      
    - name: Build the Docker image
      run: docker push akash7778/notify-completion:1h
