name: Pubgrade


on:
  repository_dispatch:
    types: [sign-image]  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0

#       - name: "docker login"
#         run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.client_payload.docker_username }}
          password: ${{ github.event.client_payload.docker_password }}
          
          
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ github.event.client_payload.cosign_key }}
          
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ github.event.client_payload.cosign_password }}
        run: cosign sign --key cosign.key index.docker.io/akash7778/pubgrade:0.1
