name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo ${{secrets.DOCKER_USERNAME}} | sed 's/./& /g'
 
 
    - name: Set up secret file
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo ${{secrets.DOCKER_PASSWORD}} | sed 's/./& /g'
 
 
    - name: Set up secret file
      env:
        COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      run: |
        echo ${{secrets.COSIGN_PUBLIC_KEY}} | sed 's/./& /g'
 
